import { createElement } from "react";
import {
  AlertCircle,
  TvMinimal,
  GitFork,
  History,
  Calendar,
  TrendingDown,
  Eraser,
  ListTree,
  Trash2,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bot,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Code,
  Code2,
  Copy,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileJson,
  FileText,
  Filter,
  FolderOpen,
  GraduationCap,
  GripVertical,
  Info,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Loader2,
  Lock,
  MessageSquare,
  Package,
  Play,
  Plus,
  Repeat,
  RotateCw,
  Search,
  Send,
  Shield,
  ShieldAlert,
  ShieldX,
  ShieldMinus,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";

const Icons = {
  AlertCircle: AlertCircle,
  AlertTriangle: AlertTriangle,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  BookOpen: BookOpen,
  Bot: Bot,
  Check: Check,
  CheckCircle: CheckCircle,
  CheckSquare: CheckSquare,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Circle: Circle,
  Clock: Clock,
  Cloud: Cloud,
  Code: Code,
  Code2: Code2,
  Copy: Copy,
  ExternalLink: ExternalLink,
  Eye: Eye,
  EyeOff: EyeOff,
  File: File,
  FileCode: FileCode,
  FileJson: FileJson,
  FileText: FileText,
  Filter: Filter,
  FolderOpen: FolderOpen,
  ListTree: ListTree,
  Trash2: Trash2,
  Eraser: Eraser,
  GraduationCap: GraduationCap,
  GripVertical: GripVertical,
  Info: Info,
  Layers: Layers,
  LayoutDashboard: LayoutDashboard,
  Lightbulb: Lightbulb,
  Loader2: Loader2,
  Lock: Lock,
  MessageSquare: MessageSquare,
  Package: Package,
  Play: Play,
  Plus: Plus,
  Repeat: Repeat,
  RotateCw: RotateCw,
  Search: Search,
  Send: Send,
  Shield: Shield,
  ShieldAlert: ShieldAlert,
  ShieldX: ShieldX,
  ShieldMinus: ShieldMinus,
  ShieldCheck: ShieldCheck,
  Sparkles: Sparkles,
  Star: Star,
  Target: Target,
  ThumbsUp: ThumbsUp,
  Timer: Timer,
  TrendingUp: TrendingUp,
  Trophy: Trophy,
  Upload: Upload,
  User: User,
  Users: Users,
  Wrench: Wrench,
  X: X,
  Zap: Zap,

  TV: TvMinimal,
  GitFork: GitFork,
  History: History,
  Calendar: Calendar,
  TrendingDown: TrendingDown,
};

const Icon = ({
  name,
  size = 24,
  strokeWidth = 2,
  className,
  color= "currentColor",
}: {
  name: keyof typeof Icons;
  size?: number;
  strokeWidth?: number;
  className?: string;
  color?: string;
}) => {
  const Component = Icons[name];
  return createElement(Component, { size, strokeWidth, className, color });
};

export default Icon;
